# Header
nav:
  # Home: /index
  Posts: /archives
  Publications: /publications
  # Projects: /projects
  About: /about
  Categories:
    path: /category
    icon: mingcute:classify-2-fill
  Tags:
    path: /tag
    icon: mingcute:tag-fill

email: "chenyingfa1999@qq.com"

# favicon
favicon: /images/favicon-32x32.png

# Portrait
portrait: /images/portrait.png

# logo
logo: /images/logo.svg

# links
links:
  Github:
    link: https://github.com/chen-yingfa
    icon: mdi:github
  ZhiHu:
    link: https://www.zhihu.com/people/chen-ying-fa-34
    icon: ri:zhihu-line
  Twitter:
    link: https://www.twitter.com/DonnyChan123
    icon: mingcute:social-x-fill
  # Weibo:

# analytics
google_analytics:
baidu_analytics:

# mathjax
fancybox: true

# mathjax
mathjax: true

# echarts
echarts: true

# busuanzi
busuanzi: true

# mermaid
mermaid:
  enable: true
  # Available themes: default | dark | forest | neutral
  theme: default

# giscus
giscus:
  enable:
  repo:
  repo_id:
  category:
  category_id:
  mapping:
